scheduler:
  revoked-token-cleanup:
    cron: '0 15 10 15 * ?'
  expired-token-cleanup:
    cron: '0 15 10 15 * ?'

jwt:
  private-key: classpath:private_key.pem
  public-key: classpath:public_key.pem
  expiration: 900000 # 15 minutes in milliseconds
  refresh-expiration: 2592000 # 30 days in seconds
  issuer: me

management:
  endpoints:
    web:
      exposure:
        include: health,info


spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true