scheduler:
  revoked-token-cleanup:
    cron: '0 15 10 15 * ?'
  expired-token-cleanup:
    cron: '0 15 10 15 * ?'

jwt:
  private-key: classpath:private_key.pem #load from .env later, here add ${JWT_PRIVATE_KEY} instead of everything
  public-key: classpath:public_key.pem # here add ${JWT_PUBLIC_KEY}
  expiration: 86400000
  refresh-expiration: 604800000

spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true